version: '2'
services:
  mysql:
    # network_mode: myNetwork
    container_name: kong_mysql
    restart: always
    image: mysql:latest # ? คล้ายๆกับ Lib แต่มันคือ image ที่ต้องการให้ทำงานอยู่กับระบบที่กำลังทำงานอยู่ mysql คือ ubuntu ที่ลง mysql ให้ แต่ ubuntu ก็คือ ubuntu
    environment:
      MYSQL_ROOT_PASSWORD: '' #? ไม่มี password
      # MYSQL_USER: 'root'
      # MYSQL_PASS: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'  #? อนุญาตให้ root ไม่ต้องมี pass
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql